// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

ScanResult evaluateItem({required String title, required Category category}) =>
    RustLib.instance.api.crateApiSimpleEvaluateItem(
      title: title,
      category: category,
    );

enum Category { clothing, furniture, books, electronics, other }

@freezed
sealed class DecisionAction with _$DecisionAction {
  const DecisionAction._();

  const factory DecisionAction.discard() = DecisionAction_Discard;
  const factory DecisionAction.bundle() = DecisionAction_Bundle;
  const factory DecisionAction.sellOn(String field0) = DecisionAction_SellOn;
}

class ScanResult {
  final DecisionAction action;
  final double estimatedValuePln;
  final double expectedNetProfitPln;
  final double saleProbability;
  final String reason;

  const ScanResult({
    required this.action,
    required this.estimatedValuePln,
    required this.expectedNetProfitPln,
    required this.saleProbability,
    required this.reason,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      estimatedValuePln.hashCode ^
      expectedNetProfitPln.hashCode ^
      saleProbability.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          estimatedValuePln == other.estimatedValuePln &&
          expectedNetProfitPln == other.expectedNetProfitPln &&
          saleProbability == other.saleProbability &&
          reason == other.reason;
}
