// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Wersja silnika — potwierdza że most Rust↔Flutter działa
Future<String> getEngineVersion() =>
    RustLib.instance.api.crateApiGetEngineVersion();

/// Główna funkcja decyzyjna — wywołana z Dart przez most
Future<ScanResult> evaluateItem({
  required Category category,
  required double estimatedValuePln,
}) => RustLib.instance.api.crateApiEvaluateItem(
  category: category,
  estimatedValuePln: estimatedValuePln,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Category>>
abstract class Category implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ScanResult>>
abstract class ScanResult implements RustOpaqueInterface {}
