//! valua_edge — UniFFI bridge between valua_core (Rust) and Kotlin (Android).
//!
//! This crate re-exports valua_core through UniFFI-annotated wrappers.
//! It compiles to libvalua_edge.so which Android loads at runtime.
//!
//! Full types and functions are added in Step 3.
//! For now this stub exposes only engine_version() so you can verify
//! the entire Rust → UniFFI → Kotlin → Android pipeline works before
//! adding any business logic.

use valua_core::engine_version as core_version;

// This macro wires up the UniFFI scaffolding generated by build.rs.
uniffi::include_scaffolding!("valua_edge");

/// Returns the engine version string.
/// This is the first function Kotlin will call — if it returns
/// "0.1.0-mvp" on the phone screen the entire bridge is confirmed working.
pub fn engine_version() -> String {
    core_version().to_string()
}
